version: "3"
services:
  django:
    build: .
    container_name: siroca
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/back_static
      - media_volumes:/usr/src/app/back_media
    restart: always
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8001"

  nginx:
    image: nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static
      - media_volumes:/usr/src/app/back_media
      - etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - django


  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - ./nginx:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot certonly --webroot -w /var/www/html --email cultanakunova@gmail.com --agree-tos --no-eff-email --staging -d clients.siroca.com && sleep 12h & wait $${!}; done;'"



volumes:
  static_volume:
  media_volumes:
  etc-letsencrypt:
