version: "3"
services:
  django:
    build: .
    container_name: siroca
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - static_volume:/usr/src/app/back_static
      - media_volumes:/usr/src/app/back_media
    restart: always
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8001"


  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/app/back_static
      - media_volumes:/usr/src/app/back_media
    depends_on:
      - django

  db:
    image: postgres
    container_name: siroca-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volumes:
  postgres_data:
