#version: '3'
#services:
#  backend:
#    build:
#      context: .
#    command: sh -c "python manage.py runserver 0.0.0.0:8000"
#    ports:
#      - "8000:8000"


  version: "3"
  services:
    django:
      build: .
      container_name: siroca
      ports:
        - "8000:8000"
      volumes:
        - .:/app
        - static_volume:/usr/src/app/back_static
        - media_volume:/usr/src/app/back_media

      restart: always
#      depends_on:
#        - pgdb
      command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000"

#    pgdb:
#      image: postgres:alpine3.19
#      environment:
#        POSTGRES_DB: ${POSTGRES_NAME}
#        POSTGRES_USER: ${POSTGRES_USER}
#        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#
#      container_name: pgdb
#      volumes:
#        - db_data:/var/lib/postgresql/data/
#      ports:
#        - "5438:5432"


    nginx:
      image: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/usr/src/app/back_static
        - media_volume:/usr/src/app/back_media
      depends_on:
        - django

  volumes:
    static_volume:
    media_volume:
    db_data: