# Generated by Django 4.2 on 2024-03-14 09:37

import apps.user.usermanager
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('auth', '0014_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role_type', models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер')], max_length=20)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='фамилия')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False, verbose_name='Менеджер')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_job_titles', to='company.jobtitle', verbose_name='Должность')),
                ('main_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='company.company', verbose_name='Компания')),
                ('managers_company', models.ManyToManyField(blank=True, related_name='managers_company', to='company.company', verbose_name='Компании менеджеров')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', apps.user.usermanager.CustomUserManager()),
            ],
        ),
    ]
