# Generated by Django 4.2 on 2024-05-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='manager_can_view_profiles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='manager_can_view_profiles_extra',
        ),
    ]
