# Generated by Django 4.2 on 2024-04-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client_can_add_checklist_extra',
            field=models.BooleanField(null=True, verbose_name='Добавление чеклиста'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_add_files_extra',
            field=models.BooleanField(null=True, verbose_name='Добавление файла'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_create_application_extra',
            field=models.BooleanField(null=True, verbose_name='Создание заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_edit_application_extra',
            field=models.BooleanField(null=True, verbose_name='Редактирование заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_edit_comments_extra',
            field=models.BooleanField(null=True, verbose_name='Добавление/удаление комментария'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_get_reports_extra',
            field=models.BooleanField(null=True, verbose_name='Отчет по заявкам(Клиент)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_view_logs_extra',
            field=models.BooleanField(null=True, verbose_name='Просмотр логов'),
        ),
    ]
