# Generated by Django 4.2 on 2024-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_can_add_checklist',
            field=models.BooleanField(default=False, verbose_name='Добавление чеклиста'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_delete_comments',
            field=models.BooleanField(default=False, verbose_name='Удаление комментариев'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_get_reports',
            field=models.BooleanField(default=False, verbose_name='Отчет по заявкам(Клиент)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_put_comments',
            field=models.BooleanField(default=False, verbose_name='Комментарий к заявке'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_view_logs',
            field=models.BooleanField(default=False, verbose_name='Просмотр логов'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_edit',
            field=models.BooleanField(default=False, verbose_name='Редактирование комментариев'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_get_reports',
            field=models.BooleanField(default=False, verbose_name='Отчет по заявкам(Менеджер)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role_type',
            field=models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер')], max_length=20, verbose_name='Тип роли'),
        ),
    ]
