# Generated by Django 4.2 on 2024-03-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_domain_alter_jobtitle_company'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.company'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='Клиент'),
        ),
    ]
