# Generated by Django 4.2 on 2024-03-23 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_relation',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='main_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='company.company', verbose_name='Компания'),
        ),
    ]
