# Generated by Django 4.2 on 2024-04-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_can_add_checklist_extra',
            field=models.BooleanField(default=False, verbose_name='Добавление чеклиста'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_add_files_extra',
            field=models.BooleanField(default=False, verbose_name='Добавление файла'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_edit_comments_extra',
            field=models.BooleanField(default=False, verbose_name='Добавление/удаление комментария'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_get_reports_extra',
            field=models.BooleanField(default=False, verbose_name='Отчет по заявкам(Клиент)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_view_logs_extra',
            field=models.BooleanField(default=False, verbose_name='Просмотр логов'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_view_profiles_extra',
            field=models.BooleanField(default=False, verbose_name='Просмотр профиля пользователей(Клиент)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_delete_application_extra',
            field=models.BooleanField(default=False, verbose_name='Удаление заявки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_delete_comments_extra',
            field=models.BooleanField(default=False, verbose_name='Удаление комментариев'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_get_reports_extra',
            field=models.BooleanField(default=False, verbose_name='Отчет по заявкам(Менеджер)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_view_profiles_extra',
            field=models.BooleanField(default=False, verbose_name='Просмотр профиля пользователей(Менеджер)'),
        ),
    ]
