# Generated by Django 4.2 on 2024-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='client_can_view_profiles',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='client_can_view_profiles_extra',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_create_application_extra',
            field=models.BooleanField(null=True, verbose_name='Создание заявки'),
        ),
    ]
