# Generated by Django 4.2 on 2024-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_client_can_add_checklist_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager_can_create_and_delete_job_title_extra',
            field=models.BooleanField(default=False, verbose_name='Просмотр списка по компаниям/пользователям/должностям'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_create_and_edit_company_extra',
            field=models.BooleanField(default=False, verbose_name='Создание/Редактирование заявки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='manager_can_create_and_edit_user_extra',
            field=models.BooleanField(default=False, verbose_name='Создание/Редактирование пользователя'),
        ),
    ]
