# Generated by Django 4.2 on 2024-04-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_manager_can_create_and_delete_job_title_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_can_create_application_extra',
            field=models.BooleanField(default=False, verbose_name='Создание заявки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='client_can_edit_application_extra',
            field=models.BooleanField(default=False, verbose_name='Редактирование заявки'),
        ),
    ]
