# Generated by Django 4.2 on 2024-03-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('user', '0003_alter_customuser_main_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='main_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='company.company', verbose_name='Компания'),
        ),
    ]
