# Generated by Django 4.2 on 2024-03-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='AdminContact',
        ),
    ]
