# Generated by Django 4.2 on 2024-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_client_can_create_application_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client_can_add_checklist_extra',
            field=models.BooleanField(default=None, verbose_name='Добавление чеклиста'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_add_files_extra',
            field=models.BooleanField(default=None, verbose_name='Добавление файла'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_create_application_extra',
            field=models.BooleanField(default=None, verbose_name='Создание заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_edit_application_extra',
            field=models.BooleanField(default=None, verbose_name='Редактирование заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_edit_comments_extra',
            field=models.BooleanField(default=None, verbose_name='Добавление/удаление комментария'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_get_reports_extra',
            field=models.BooleanField(default=None, verbose_name='Отчет по заявкам(Клиент)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_view_logs_extra',
            field=models.BooleanField(default=None, verbose_name='Просмотр логов'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='client_can_view_profiles_extra',
            field=models.BooleanField(default=None, verbose_name='Просмотр профиля пользователей(Клиент)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_create_and_delete_job_title_extra',
            field=models.BooleanField(default=None, verbose_name='Просмотр списка по компаниям/пользователям/должностям'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_create_and_edit_company_extra',
            field=models.BooleanField(default=None, verbose_name='Создание/Редактирование заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_create_and_edit_user_extra',
            field=models.BooleanField(default=None, verbose_name='Создание/Редактирование пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_delete_application_extra',
            field=models.BooleanField(default=None, verbose_name='Удаление заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_delete_comments_extra',
            field=models.BooleanField(default=None, verbose_name='Удаление комментариев'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_get_reports_extra',
            field=models.BooleanField(default=None, verbose_name='Отчет по заявкам(Менеджер)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_view_profiles_extra',
            field=models.BooleanField(default=None, verbose_name='Просмотр профиля пользователей(Менеджер)'),
        ),
    ]
