# Generated by Django 4.2 on 2024-03-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_domain_alter_jobtitle_company'),
        ('user', '0005_rename_contact_admincontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admincontact',
            options={'verbose_name': 'Контакт для админа', 'verbose_name_plural': 'Контакты для админа'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='company.company', verbose_name='отношения с компанией'),
        ),
    ]
