# Generated by Django 4.2 on 2024-04-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_manager_can_create_and_delete_job_title_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_create_and_delete_job_title_extra',
            field=models.BooleanField(null=True, verbose_name='Просмотр списка по компаниям/пользователям/должностям'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_create_and_edit_company_extra',
            field=models.BooleanField(null=True, verbose_name='Создание/Редактирование заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_create_and_edit_user_extra',
            field=models.BooleanField(null=True, verbose_name='Создание/Редактирование пользователя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_delete_application_extra',
            field=models.BooleanField(null=True, verbose_name='Удаление заявки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_delete_comments_extra',
            field=models.BooleanField(null=True, verbose_name='Удаление комментариев'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_get_reports_extra',
            field=models.BooleanField(null=True, verbose_name='Отчет по заявкам(Менеджер)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='manager_can_view_profiles_extra',
            field=models.BooleanField(null=True, verbose_name='Просмотр профиля пользователей(Менеджер)'),
        ),
    ]
