# Generated by Django 4.2 on 2024-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='job_titles',
            field=models.ManyToManyField(related_name='companies', to='company.jobtitle', verbose_name='Должности'),
        ),
    ]
