# Generated by Django 4.2 on 2024-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='user.userprofile', verbose_name='Пользователи'),
        ),
    ]
