# Generated by Django 4.2 on 2024-04-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='Краткий код'),
        ),
    ]
