# Generated by Django 4.2 on 2024-02-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Сделать', 'Сделать'), ('В работе', 'В работе'), ('Тестируется', 'Тестируется'), ('Перекрыто', 'Перекрыто'), ('На обновлении', 'На обновлении'), ('Закрыто', 'Закрыто')], max_length=100, null=True)),
                ('priority', models.CharField(choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], max_length=100, null=True)),
                ('jira', models.URLField(null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('confirm_date', models.PositiveIntegerField(null=True)),
                ('offer_date', models.PositiveIntegerField(null=True)),
                ('payment_state', models.CharField(choices=[('Оплачено', 'Оплачено'), ('Ожидание оплаты', 'Ожидание оплаты'), ('Не оплачено', 'Не оплачено')], max_length=100, null=True)),
                ('start_date', models.PositiveIntegerField(null=True)),
                ('finish_date', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('files', models.ImageField(null=True, upload_to='')),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('comments_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
