# Generated by Django 4.2 on 2024-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='made_change',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
