# Generated by Django 4.2 on 2024-05-10 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlogs',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='check_list_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.checklist', verbose_name='id чеклиста'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='field',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='file_logs',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл картинки'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='application.applicationform', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='initially',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='new',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='applicationlogs',
            name='user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id пользователя'),
        ),
    ]
