# Generated by Django 4.2 on 2024-05-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlogs',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
