# Generated by Django 4.2 on 2024-04-02 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='confirm_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата утверждения заявки'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='files',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='jira',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка JIRA'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='main_client',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_manager': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_application', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='main_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_manager': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_application', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='offer_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отправки КП'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='payment_state',
            field=models.CharField(blank=True, choices=[('Оплачено', 'Оплачено'), ('Ожидание оплаты', 'Ожидание оплаты'), ('Не оплачено', 'Не оплачено')], max_length=100, null=True, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='priority',
            field=models.CharField(blank=True, choices=[('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий')], max_length=100, null=True, verbose_name='Приоритет заявки'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.CharField(blank=True, choices=[('К выполнению', 'К выполнению'), ('В работе', 'В работе'), ('Тестируется', 'Тестируется'), ('Перекрыто', 'Перекрыто'), ('На обновлении', 'На обновлении'), ('Закрыто', 'Закрыто')], default='К выполнению', max_length=100, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Название заявки'),
        ),
    ]
