# Generated by Django 4.2 on 2024-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlogs',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
