# Generated by Django 4.2 on 2024-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='check_list',
            field=models.ManyToManyField(blank=True, related_name='checklist', to='application.checklist', verbose_name='Чек-лист'),
        ),
    ]
