# Generated by Django 4.2 on 2024-04-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_client',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
