# Generated by Django 4.2 on 2024-03-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_notification_made_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
