# Generated by Django 4.2 on 2024-04-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogs',
            name='expiration_time',
        ),
    ]
