# Generated by Django 4.2 on 2024-05-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='count_applications', to='company.company', verbose_name='Компания'),
        ),
    ]
