# Generated by Django 4.2 on 2024-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicationlogs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlogs',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
