# Generated by Django 4.2 on 2024-05-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applicationlogs_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
