# Generated by Django 4.2 on 2024-04-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_notification_is_client_notification_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expiration_time',
        ),
    ]
