# Generated by Django 4.2 on 2024-04-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applicationform_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='application',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='check_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.checklist', verbose_name='Чек-лист'),
        ),
    ]
