# Generated by Django 4.2 on 2024-03-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
