# Generated by Django 4.2 on 2024-02-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applicationform_application_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationform',
            options={'verbose_name': ('Заявка',), 'verbose_name_plural': 'Заявки'},
        ),
    ]
