# Generated by Django 4.2 on 2024-04-27 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_remove_applicationlogs_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlogs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Файлы'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='priority',
            field=models.CharField(blank=True, choices=[('Самый низкий', 'Самый низкий'), ('Низкий', 'Низкий'), ('Средний', 'Средний'), ('Высокий', 'Высокий'), ('Самый высокий', 'Самый высокий')], default='Средний', max_length=100, verbose_name='Приоритет заявки'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
    ]
