# Generated by Django 4.2 on 2024-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_notification_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
    ]
