# Generated by Django 4.2 on 2024-05-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_applicationlogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlogs',
            name='file_logs',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
