# Generated by Django 4.2 on 2024-04-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_notification_expiration_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_client',
            new_name='is_client_notic',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_manager',
            new_name='is_manager_notic',
        ),
    ]
