# Generated by Django 4.2 on 2024-04-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_applicationlogs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlogs',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
