# Generated by Django 4.2 on 2024-02-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_applicationform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='task_number',
            field=models.PositiveIntegerField(max_length=20, null=True, verbose_name='Номер заявки'),
        ),
    ]
