# Generated by Django 4.2 on 2024-04-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_applicationlogs_user_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationlogs',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
