# Generated by Django 4.2 on 2024-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_applicationlogs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationlogs',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
