# Generated by Django 4.2 on 2024-03-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_notification_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_sent',
        ),
    ]
