# Generated by Django 4.2 on 2024-02-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_applicationform_task_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='task_number',
            field=models.PositiveIntegerField(null=True, verbose_name='Номер заявки'),
        ),
    ]
