# Generated by Django 4.2 on 2024-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_applicationlogs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogs',
            name='text',
        ),
        migrations.AddField(
            model_name='applicationlogs',
            name='field',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicationlogs',
            name='initially',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='applicationlogs',
            name='new',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
