# Generated by Django 4.2 on 2024-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_is_client_notification_is_client_notic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
